server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4201"
              - "http://localhost:4202"
              - "http://localhost:4203"
              - "http://localhost:4204"
              - "http://localhost:4205"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        # PUBLIC ROUTES: No Filter
        - id: auth-public
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/login, /api/auth/register

        # PRIVATE ROUTES: Needs the Guard
        - id: tracker-service
          uri: lb://tracker-service
          predicates:
            - Path=/api/projects/**, /api/tasks/**
          filters:
            - JwtAuthenticationFilter

        - id: auth-internal-lookups
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/users/**
          filters:
            - JwtAuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
    # REMOVE the ip-address: 127.0.0.1 line if you want other services to see the Gateway
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/